### ISSUE TITLE
Doesn't find table!

### ISSUE THREAD

**Issue by vlulla** [gambolputty/wikitable2csv#1]
Cannot find any table on https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)_per_capita

I also tried https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)_per_capita#List_of_per_capita_nominal_GDP_for_countries_and_dependencies

Additionally, is there a possibility to select only one table?  For e.g., I'm interested only in the IMF table.

Thanks in advance.

**Comment by gambolputty** [comment]
Fixed it! [http://wikitable2csv.ggor.de](http://wikitable2csv.ggor.de)

**Comment by gambolputty** [comment]
It should give you any table found on the Wikipedia page, each table inside a textarea in CSV-format. You can select your desired table from these results.

**Comment by gambolputty** [comment]
Still buggy. I'm reopening this issue.

**Comment by gambolputty** [comment]
I made some further testing. It should work now.

**Comment by vlulla** [comment]
Thank you!  Works like a charm.
