### ISSUE TITLE
table rows messed

### ISSUE THREAD

**Issue by void285** [gambolputty/wikitable2csv#10]
I try to convert the tables in the following url:

[https://zh.wikipedia.org/wiki/%E8%BE%BD%E6%9C%9D%E5%90%9B%E4%B8%BB%E5%88%97%E8%A1%A8#.E8.A5.BF.E8.BE.BD](url)

The  2nd table have complex rowspan settings, and the result messed up. Some content in following lines appear in the leading lines. For example, **",耶律亿,阿保机,872年-926年,神册、天赞、天显,907年-926年"** in the 4th line are from the 1st line.

>1 太祖,升天皇帝 （926年太宗初谥）,耶律亿,阿保机,872年-926年,神册、天赞、天显,907年-926年
>2 太祖,大圣大明天皇帝 （1008年圣宗加谥）
>3 太祖,大圣大明神烈天皇帝 （1052年兴宗加谥）
>4 ,贞烈皇后 （953年穆宗初谥）,**耶律亿,阿保机,872年-926年,神册、天赞、天显,907年-926年**,述律平 （称制）,月理朵,879年-953年,天显,926年-927年
>5 ,淳钦皇后 （1052年兴宗改谥）

**Comment by gambolputty** [comment]
I would like to help, but I have difficulties examining this issue, mainly because I cannot read the alphabet of this language. Do you have another example with latin characters?

**Comment by gambolputty** [comment]
I found another example on my own and I'm investigating the issue for table number 4 on [this](https://en.wikipedia.org/wiki/2002_FIFA_World_Cup) page.

**Comment by gambolputty** [comment]
I think I fixed the issue. Could you please check if the problem persists? --> [http://wikitable2csv.ggor.de](http://wikitable2csv.ggor.de/)

I was testing it for example with the following pages:
1. https://en.wikipedia.org/wiki/List_of_participating_nations_at_the_Summer_Olympic_Games
2. https://en.wikipedia.org/wiki/List_of_world_sports_championships

**Comment by void285** [comment]
Hello, I checked the page and the result is OK.
Wonderfull work, thanks!

The page: https://zh.wikipedia.org/wiki/%E8%BE%BD%E6%9C%9D%E5%90%9B%E4%B8%BB%E5%88%97%E8%A1%A8#.E8.A5.BF.E8.BE.BD,

**Comment by gambolputty** [comment]
Thanks a lot for your help and feedback :)
Closing this issue now.
