### ISSUE TITLE
I want to convert mediawiki table data to csv. How can this be achieved?

### ISSUE THREAD

**Issue by goldingdamien** [gambolputty/wikitable2csv#12]
I want to convert mediawiki data to csv. I want to use either text or a file. Is this possible?

https://www.mediawiki.org/wiki/Help:Tables

**Comment by gambolputty** [comment]
I'm not sure I understand correctly. Do you want to insert Wikitext (source code of Wiki pages) into an input field and have it converted to CSV? It would be helpful if you could explain in detail what you want. Thanks!

**Comment by goldingdamien** [comment]
My understanding of this project is that it takes a URL of a webpage to perform actions. I am not sure if this is limited to external websites OR if there is a way to handle a string. 
I want to convert mediawiki data to csv which is locally saved.

**Comment by rubo77** [comment]
As a workaround you can copy the source of your local Wikimedia page and create sandbox page on Wikipedia.

Then you can use the URL of that sandbox page

**Comment by gambolputty** [comment]
@goldingdamien it is limited to external wiki pages.
It extracts the page title from the input url and sends an ajax requests to the api endpoint of the wiki. The api returns a html version of the page, which has html tables that are converted to csv.

**Comment by gambolputty** [comment]
Take a look at the [Wikipedia:Tools](https://en.wikipedia.org/wiki/Wikipedia:Tools) page. May be you find something useful there. I'm closing this issue, since the requested feature is not planned.

**Comment by goldingdamien** [comment]
Ok, thanks.
