### ISSUE TITLE
phantomjs install error and Errorpage on start

### ISSUE THREAD

**Issue by rubo77** [gambolputty/wikitable2csv#14]
On my Ubuntu 18.04 I started with `npm install` and this seemed to work at first, but after some minutes I got this error:

```

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN bootstrap@4.1.2 requires a peer of popper.js@^1.14.3 but none was installed.
npm ERR! Linux 4.16.0-041600-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/wikitable2csv/npm-debug.log

$ nodejs --version
v8.10.0
$ npm --version
3.5.2
```

**Comment by gambolputty** [comment]
PhantomJS ist used by the test runner and I don't have a Ubuntu system to reproduce this. I'm sorry, but I can only recommend a [Google search](https://www.google.de/search?q=%22Failed+at+the+phantomjs-prebuilt%402.1.16+install+script+%27node+install.js%27.%22&rlz=1C1CHBF_deDE784DE784&oq=%22Failed+at+the+phantomjs-prebuilt%402.1.16+install+script+%27node+install.js%27.%22&aqs=chrome..69i57.592j0j7&sourceid=chrome&ie=UTF-8) to you, since the problem with the `phantomjs-prebuilt` package seems to be known and I don't have the time to work on this at the moment :/

**Comment by rubo77** [comment]
It seems like installing phantomjs as root works fine:

    sudo npm install -g phantomjs-prebuilt

running `npm install` again then just shows this warning left:

    └── UNMET PEER DEPENDENCY popper.js@^1.14.3

Seems just a warning, don't know if that is OK?

**Comment by rubo77** [comment]
And now?

How do I run the app, so I can see it in my browser?

**Comment by rubo77** [comment]
After starting the app with

    gulp

 I get this error:

    ReferenceError: Can't find variable: app

    local:18
    :0 in setContent
    :2

the main page reloads a few times with different wikipeia pages, for example 

> https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Rapports/Nombre_de_pages_par_namespace

and then sais:

>Error parsing Wikipedia url. Please enter a valid Wikipedia url (e. g. https://en.wikipedia.org/wiki/List_of_airports)


```
finished in 53.287s7 specs, 2 failuresSpec List | Failures
Output is 4 tables for url 1
Expected 7 to be 4.
stack@http://localhost:8888/:2514:17
buildExpectationResult@http://localhost:8888/:2484:14
expectationResultFactory@http://localhost:8888/:960:18
Spec.prototype.addExpectationResult@http://localhost:8888/:583:29
addExpectationResult@http://localhost:8888/:904:16
Expectation.prototype.wrapCompare/<@http://localhost:8888/:2428:7
@http://localhost:8888/spec/app_spec.js:16:7
Output is 0 tables for wrong url
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in http://localhost:8888/ (line 4529)
attempt/timeoutId<@http://localhost:8888/:4529:23
```

**Comment by gambolputty** [comment]
I'm rewriting the code at the moment. This will be fixed in the next release.

**Comment by rubo77** [comment]
Which commit was the last running state?

Can you add a tag there?

**Comment by rubo77** [comment]
thanks, with the latest commit 77f2b5a it works fine
