### ISSUE TITLE
How do I run the app, so I can see it in my browser?

### ISSUE THREAD

**Issue by rubo77** [gambolputty/wikitable2csv#16]
After a successfull installation I am now stuck.

Please add info how to run the app to the readme.

**Comment by gambolputty** [comment]
Can you provide information on _where_ you are stuck? What is _not_ working?

**Comment by rubo77** [comment]
I have cloned the repository, started

    npm install

and now?

what is the url, I can see the app?

I would like to have a page like this: http://wikitable2csv.ggor.de/ on my local mashine, but which url? which port?

http://localhost/ doesn't show the app ;)

**Comment by rubo77** [comment]
I tried

    cd src/
    python -m SimpleHTTPServer
    
now I can see the app in http://localhost:8000/ but it is not working

**Comment by rubo77** [comment]
Ah I see, I have to start 

    gulp

in the wikitable2csv folder and then I can see the app in http://localhost:8888/
