### ISSUE TITLE
API encoding url

### ISSUE THREAD

**Issue by framawiki** [gambolputty/wikitable2csv#2]
Try with this link: https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Rapports/Nombre_de_pages_par_namespace

The tool will call https://fr.wikipedia.org/api/rest_v1/page/html/Wikip%C3%A9dia:Rapports/Nombre_de_pages_par_namespace
But this link is the good one: https://fr.wikipedia.org/api/rest_v1/page/html/Wikip%C3%A9dia%3ARapports%2FNombre_de_pages_par_namespace

Perhaps it's a problem from the api server too.
Thanks

**Comment by framawiki** [comment]
Perhaps you can remove the `decode` function of https://github.com/gambolputty/wikitable2csv/blob/7c49931480516928fccf100e0bb916a23c6d42d5/src/js/scripts.js#L83

**Comment by framawiki** [comment]
Yes, it works.

**Comment by gambolputty** [comment]
Hey @framawiki, thanks for taking care! Will get to the code soon and check out your solution.

Many thanks,
Gregor

**Comment by gambolputty** [comment]
There was an encoding error with the former API causing several other errors. I therefore switched to the official Mediawiki-API to parse an article (e.g. `https://fr.wikipedia.org/w/api.php?action=parse&format=json&origin=*&page=Wikip%C3%A9dia:Rapports/Nombre_de_pages_par_namespace&prop=text`).

Should work fine now.
