### ISSUE TITLE
Table grids missed

### ISSUE THREAD

**Issue by void285** [gambolputty/wikitable2csv#25]
I try to convert this url:

https://zh.wikipedia.org/wiki/%E5%85%83%E6%9C%9D%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92

All grids data in other than the first three columns missed in the result.

**Comment by gambolputty** [comment]
I think I fixed it. Could you check again? --> [http://wikitable2csv.ggor.de/](http://wikitable2csv.ggor.de) 

Thanks again for reporting!

**Comment by void285** [comment]
It works as expected now, thanks!
