### ISSUE TITLE
make filename more specific

### ISSUE THREAD

**Issue by chapmanjacobd** [gambolputty/wikitable2csv#28]
https://github.com/gambolputty/wikitable2csv/blob/de8898e5c867f515c5979ce6579ae0abb30d7625/src/ui/index.js#L193

How could I edit this so that the title of the wikipedia article is also added in front of blockId?

**Comment by gambolputty** [comment]
I rewrote [the app](https://wikitable2csv.ggor.de/). The file names are now in the format `<wiki page title>_<table number>.csv`.
