### ISSUE TITLE
Enable csv file as response

### ISSUE THREAD

**Issue by timp** [gambolputty/wikitable2csv#48]
It would be really useful, to me, to be able to switch whether the output is returned in the current way or as a file, named for the page url.

**Comment by gambolputty** [comment]
Hello, I'm not sure if I understand. When there are multiple tables on one wiki page, this tools gives multiple tables as a result, which may have different table heads and structure. Merging them into one file is not suitable in other cases. I rewrote the app and for now each table that can be downloaded has a file name in the format of `<wiki_page_title>_<table_number>.csv`. Hope, that helps.

**Comment by timp** [comment]
Thank you.
