### ISSUE TITLE
Allow to parse other wikis than Wikipedia

### ISSUE THREAD

**Issue by framawiki** [gambolputty/wikitable2csv#7]
I want to get the table that is present on https://meta.wikimedia.org/wiki/2017_Community_Wishlist_Survey/Results, but as it's not WP, I can't :(

**Comment by gambolputty** [comment]
It should work now :)
I tested it with Wikimedia.org- and Wikibooks.org-URLs. Other Wikis that support API access should also too If not, please open another issue.
