### ISSUE TITLE
Could you please add a button to copy all tables?

### ISSUE THREAD

**Issue by void285** [gambolputty/wikitable2csv#8]
Thanks for the good tool, it's very useful!
Sometimes the tables on the page are of same format, so if there is a  button to copy all contents, it will save a lot of time.

**Comment by gambolputty** [comment]
Done :)
When there is more than one table in the results, a button to copy all tables at once is now added to the output container. All tables are seperated by an empty line.

**Comment by void285** [comment]
Great work! Thanks!
